# Generated by Django 5.0.4 on 2024-04-16 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('administrator', 'Admin'), ('user', 'User')], max_length=15),
        ),
    ]
