# Generated by Django 5.0.4 on 2024-04-18 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_user_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('administrator', 'administrator'), ('user', 'user')], default='user', max_length=15),
        ),
    ]
