openapi: 3.0.3
info:
  title: IIV Akademiyasi moddiy boyliklarini hisobga olish uchun Backend qismi
  version: 1.0.0
  description: IIV Akademiyasi moddiy boyliklarini hisobga olish, nazorat qilish uchun
    Backend qismi
paths:
  /api/auth/login/:
    post:
      operationId: auth_login_create
      description: Foydalanuvchi login qilishi uchun endpoint.
      summary: User login qilishi uchun endpoint
      tags:
      - Avtorizatsiyaga oid endpointlar
      requestBody:
        content:
          application/x-www-form-urlencoded:
            schema:
              $ref: '#/components/schemas/AuthToken'
          multipart/form-data:
            schema:
              $ref: '#/components/schemas/AuthToken'
          application/json:
            schema:
              $ref: '#/components/schemas/AuthToken'
        required: true
      security:
      - tokenAuth: []
      responses:
        '200':
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/User'
          description: ''
  /api/auth/logout/:
    post:
      operationId: auth_logout_create
      description: Tizimdan chiqish uchun endpoint.
      summary: Tizimdan chiqish uchun endpoint
      tags:
      - Avtorizatsiyaga oid endpointlar
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/User'
          application/x-www-form-urlencoded:
            schema:
              $ref: '#/components/schemas/User'
          multipart/form-data:
            schema:
              $ref: '#/components/schemas/User'
        required: true
      security:
      - tokenAuth: []
      responses:
        '200':
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/User'
          description: ''
  /api/auth/register/:
    post:
      operationId: auth_register_create
      description: Registratsiya qilish
      summary: Foydalanuvchi registratsiya qilishi uchun endpoint
      tags:
      - Avtorizatsiyaga oid endpointlar
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/User'
          application/x-www-form-urlencoded:
            schema:
              $ref: '#/components/schemas/User'
          multipart/form-data:
            schema:
              $ref: '#/components/schemas/User'
        required: true
      security:
      - tokenAuth: []
      - {}
      responses:
        '200':
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/User'
          description: ''
  /api/products/:
    get:
      operationId: products_list
      description: Barcha mahsulotlar ro'yxati
      summary: Barcha mahsulotlar ro'yxati
      tags:
      - Moddiy boyliklarga oid endpointlar
      security:
      - tokenAuth: []
      responses:
        '200':
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Product'
          description: ''
  /api/products/{id}/:
    get:
      operationId: products_list_2
      description: Id si ko'rsatilgan mahsulot
      summary: Id si ko'rsatilgan mahsulot
      parameters:
      - in: path
        name: id
        schema:
          type: integer
        required: true
      tags:
      - Moddiy boyliklarga oid endpointlar
      security:
      - tokenAuth: []
      responses:
        '200':
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Product'
          description: ''
  /api/products/{id}/delete/:
    delete:
      operationId: products_delete_destroy
      description: Mahsulotni o'chirib tashlash
      summary: Mahsulotni o'chirib tashlash
      parameters:
      - in: path
        name: id
        schema:
          type: integer
        required: true
      tags:
      - Moddiy boyliklarga oid endpointlar
      security:
      - tokenAuth: []
      responses:
        '200':
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Product'
          description: ''
  /api/products/{id}/update/:
    put:
      operationId: products_update_update
      description: Mahsulotga o'zgartirish kiritish
      summary: Mahsulotga o'zgartirish kiritish
      parameters:
      - in: path
        name: id
        schema:
          type: integer
        required: true
      tags:
      - Moddiy boyliklarga oid endpointlar
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Product'
          application/x-www-form-urlencoded:
            schema:
              $ref: '#/components/schemas/Product'
          multipart/form-data:
            schema:
              $ref: '#/components/schemas/Product'
        required: true
      security:
      - tokenAuth: []
      responses:
        '200':
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Product'
          description: ''
  /api/products/create/:
    post:
      operationId: products_create_create
      description: 'Mahsulot yaratish: bunda POST metodi ishlatiladi'
      summary: Mahsulot yaratish
      tags:
      - Moddiy boyliklarga oid endpointlar
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Product'
          application/x-www-form-urlencoded:
            schema:
              $ref: '#/components/schemas/Product'
          multipart/form-data:
            schema:
              $ref: '#/components/schemas/Product'
        required: true
      security:
      - tokenAuth: []
      responses:
        '200':
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Product'
          description: ''
  /api/schema/:
    get:
      operationId: schema_retrieve
      description: drf spectacular sxemasi
      summary: drf spectacular sxemasi
      parameters:
      - in: query
        name: format
        schema:
          type: string
          enum:
          - json
          - yaml
      - in: query
        name: lang
        schema:
          type: string
          enum:
          - af
          - ar
          - ar-dz
          - ast
          - az
          - be
          - bg
          - bn
          - br
          - bs
          - ca
          - ckb
          - cs
          - cy
          - da
          - de
          - dsb
          - el
          - en
          - en-au
          - en-gb
          - eo
          - es
          - es-ar
          - es-co
          - es-mx
          - es-ni
          - es-ve
          - et
          - eu
          - fa
          - fi
          - fr
          - fy
          - ga
          - gd
          - gl
          - he
          - hi
          - hr
          - hsb
          - hu
          - hy
          - ia
          - id
          - ig
          - io
          - is
          - it
          - ja
          - ka
          - kab
          - kk
          - km
          - kn
          - ko
          - ky
          - lb
          - lt
          - lv
          - mk
          - ml
          - mn
          - mr
          - ms
          - my
          - nb
          - ne
          - nl
          - nn
          - os
          - pa
          - pl
          - pt
          - pt-br
          - ro
          - ru
          - sk
          - sl
          - sq
          - sr
          - sr-latn
          - sv
          - sw
          - ta
          - te
          - tg
          - th
          - tk
          - tr
          - tt
          - udm
          - ug
          - uk
          - ur
          - uz
          - vi
          - zh-hans
          - zh-hant
      tags:
      - Endpoint sxemasi
      security:
      - tokenAuth: []
      - {}
      responses:
        '200':
          content:
            application/vnd.oai.openapi:
              schema:
                type: object
                additionalProperties: {}
            application/yaml:
              schema:
                type: object
                additionalProperties: {}
            application/vnd.oai.openapi+json:
              schema:
                type: object
                additionalProperties: {}
            application/json:
              schema:
                type: object
                additionalProperties: {}
          description: ''
components:
  schemas:
    AuthToken:
      type: object
      properties:
        username:
          type: string
          writeOnly: true
        password:
          type: string
          writeOnly: true
        token:
          type: string
          readOnly: true
      required:
      - password
      - token
      - username
    Product:
      type: object
      properties:
        id:
          type: integer
          readOnly: true
        inn_code:
          type: string
          maxLength: 10
        name:
          type: string
          maxLength: 100
        description:
          type: string
        price:
          type: string
          format: decimal
          pattern: ^-?\d{0,3}(?:\.\d{0,2})?$
        quantity:
          type: integer
          maximum: 9223372036854775807
          minimum: 0
          format: int64
        date_created:
          type: string
          format: date-time
          readOnly: true
        expiry_date:
          type: string
          format: date
          nullable: true
        brand:
          type: string
          maxLength: 100
        product_image:
          type: string
          format: uri
        category:
          type: integer
        warehouse:
          type: integer
        user:
          type: integer
        supplier:
          type: integer
      required:
      - brand
      - category
      - date_created
      - description
      - id
      - inn_code
      - name
      - price
      - quantity
      - supplier
      - user
      - warehouse
    RoleEnum:
      enum:
      - administrator
      - user
      type: string
      description: |-
        * `administrator` - administrator
        * `user` - user
    User:
      type: object
      properties:
        username:
          type: string
          description: Required. 150 characters or fewer. Letters, digits and @/./+/-/_
            only.
          pattern: ^[\w.@+-]+$
          maxLength: 150
        email:
          type: string
          format: email
          title: Email address
          maxLength: 254
        role:
          $ref: '#/components/schemas/RoleEnum'
        password:
          type: string
          writeOnly: true
          maxLength: 128
      required:
      - password
      - username
  securitySchemes:
    tokenAuth:
      type: apiKey
      in: header
      name: Authorization
      description: Token-based authentication with required prefix "Token"
