# Generated by Django 5.0.4 on 2024-04-17 06:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='supplier',
            name='contact_number',
            field=models.CharField(default='test', max_length=11),
            preserve_default=False,
        ),
    ]
