# Generated by Django 5.0.4 on 2024-05-13 13:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0013_alter_product_id'),
    ]

    operations = [
        migrations.DeleteModel(
            name='QRCode',
        ),
    ]
