# Generated by Django 5.0.4 on 2024-05-13 13:36

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0015_alter_product_date_created'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='date_created',
            field=models.DateField(default=datetime.datetime(2024, 5, 13, 13, 36, 15, 200452, tzinfo=datetime.timezone.utc)),
        ),
    ]
